name = "ai-social-api"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]
account_id = "9a5ff316a26b8abb696af519e515d2de"

[vars]
# 提示：生产环境请通过 wrangler secrets 注入敏感变量；本地 DEV 配置使用 .dev.vars
DEV_MODE = "1"
R2_PUBLIC_UPLOAD_BASE = "https://pub-59ae9a96b6614a9db89af40b2970d3ab.r2.dev"
R2_PUBLIC_AFTER_BASE = "https://pub-c6cdf19c1dc84237813b1f66cf8afeff.r2.dev"
ALLOWED_ORIGIN = "https://cuttingasmr.org"
CLERK_ISSUER = "https://cuttingasmr.org"
CLERK_JWKS_URL = "https://cuttingasmr.org/.well-known/jwks.json"

[[d1_databases]]
binding = "DB"
database_name = "test-d1"
database_id = "f3ca59bf-89fc-43ba-bb9c-ee253242b838"

[[r2_buckets]]
binding = "R2_UPLOAD"
bucket_name = "test-upload"

[[r2_buckets]]
binding = "R2_AFTER"
bucket_name = "test-after"

[triggers]
crons = ["*/15 * * * *"]


# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# 路由配置 - 确保API路由指向Worker
[[routes]]
pattern = "cuttingasmr.org/api/*"
zone_name = "cuttingasmr.org"


