name = "ai-social-api"
main = "src/index.ts"
compatibility_date = "2024-06-01"
account_id = "9a5ff316a26b8abb696af519e515d2de"
account_id = "9a5ff316a26b8abb696af519e515d2de"

[vars]
# Upstash REST (set via wrangler secret for TOKEN)
UPSTASH_REDIS_REST_URL = "https://giving-antelope-48894.upstash.io"

[[d1_databases]]
binding = "DB"
database_name = "test-d1"
database_id = "f3ca59bf-89fc-43ba-bb9c-ee253242b838"

[[r2_buckets]]
binding = "R2_UPLOAD"
bucket_name = "test-upload"

[[r2_buckets]]
binding = "R2_AFTER"
bucket_name = "test-after"

[triggers]
crons = ["*/15 * * * *"]


