name = "ai-social-api"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]
account_id = "9a5ff316a26b8abb696af519e515d2de"

[vars]
# 提示：生产环境请通过 wrangler secrets 注入敏感变量；本地 DEV 配置使用 .dev.vars
DEV_MODE = "0"
R2_PUBLIC_UPLOAD_BASE = "https://pub-59ae9a96b6614a9db89af40b2970d3ab.r2.dev"
R2_PUBLIC_AFTER_BASE = "https://pub-c6cdf19c1dc84237813b1f66cf8afeff.r2.dev"
ALLOWED_ORIGIN = "https://cuttingasmr.org"
# Payments (Creem)
CREEM_API_BASE_URL = "https://api.creem.dev"
CREEM_SUCCESS_URL = "https://cuttingasmr.org/user/me"
CREEM_CANCEL_URL = "https://cuttingasmr.org/user/me"
CLERK_ISSUER = "https://clerk.cuttingasmr.org"
CLERK_JWKS_URL = "https://clerk.cuttingasmr.org/.well-known/jwks.json"
CLERK_JWT_KEY = "19940214"

# KIE API 配置
KIE_API_BASE_URL = "https://api.kie.ai/api/v1/flux/kontext"
KIE_DEFAULT_MODEL = "flux-kontext-pro"
KIE_DEFAULT_ASPECT_RATIO = "1:1"
KIE_DEFAULT_OUTPUT_FORMAT = "png"
KIE_DEFAULT_SAFETY_TOLERANCE = "2"
KIE_CALLBACK_URL = "https://cuttingasmr.org/api/kie/kie-callback"
# KIE_API_KEY 应该通过 wrangler secret 设置，不要在此文件中明文存储



# Redis 配置 (Upstash)
# 注意：生产环境中应该通过 wrangler secret 设置这些敏感变量
# UPSTASH_REDIS_REST_URL = "your_redis_url_here"
# UPSTASH_REDIS_REST_TOKEN = "your_redis_token_here"

# 敏感配置 - 生产环境请使用 wrangler secret put 命令设置
# wrangler secret put KIE_API_KEY
# wrangler secret put UPSTASH_REDIS_REST_URL  
# wrangler secret put UPSTASH_REDIS_REST_TOKEN
# wrangler secret put CLERK_SECRET_KEY
# wrangler secret put ADMIN_TOKEN

# Creem API 配置
# wrangler secret put CREEM_API_KEY
# wrangler secret put CREEM_WEBHOOK_SECRET

[[d1_databases]]
binding = "DB"
database_name = "test-d1"
database_id = "f3ca59bf-89fc-43ba-bb9c-ee253242b838"

[[r2_buckets]]
binding = "R2_UPLOAD"
bucket_name = "test-upload"

[[r2_buckets]]
binding = "R2_AFTER"
bucket_name = "test-after"

[triggers]
crons = ["*/15 * * * *"]


# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# 路由配置 - 确保API路由指向Worker
[[routes]]
pattern = "cuttingasmr.org/api/*"
zone_name = "cuttingasmr.org"


